// Title:        Texture Max Load Editor Default Settings
// Description:  This file holds default settings data for the Texture Max Load Editor
//
// Note:         The Texture Max Load Editor will not work if this file is edited in any way

[RESOLUTIONS]
0=256,Medium
1=512,High
2=1024,Very High
3=2048,HD
4=4096,SHD

[OPTIONS.GENERAL]
runfsx=0
runwin=0
minimize=0
sub=0

[OPTIONS.AUTO]
auto=0
resolution=4096
application=
close=0

[MISCELLANEOUS]
tooltips=1
autotime=9
